language: android
android:
  components:
    - android-27
    - android-29
    - tools
    - platform-tools
    - build-tools-29.0.3
    - sys-img-x86-google_apis-27
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew clean assembleDebug assembleRelease testDebug app:connectedAndroidTest

before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.3"

before_script:
  - android list target
  - echo no | android create avd --force -n test -t android-27 --abi x86 -c 100M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
